<a href="https://colab.research.google.com/github/KrischelleJoyner/DataSciencePortfolio/blob/main/Python/Train%20and%20Test%20Sets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install scikit-learn

In [ ]:
#Problem 1
import pandas as pd
import numpy as np
import sklearn as sklearn
url='http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
names=['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model year', 'origin', 'car name']

In [ ]:
#loading dataset
mpg_data = pd.read_csv(url, names=names, header=None, delim_whitespace=True, na_values = ['?', ' ?', ' ? ', '? '])
mpg_data.shape

(398, 9)

In [ ]:
#first 5 rows of data
mpg_data.head(5)

mpg  cylinders  displacement  ...  model year  origin                   car name
0  18.0          8         307.0  ...          70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...          70       1          buick skylark 320
2  18.0          8         318.0  ...          70       1         plymouth satellite
3  16.0          8         304.0  ...          70       1              amc rebel sst
4  17.0          8         302.0  ...          70       1                ford torino

[5 rows x 9 columns]

In [ ]:
#removing car name column
new_mpg_data = mpg_data.drop(columns=['car name'])
#summary of data
new_mpg_data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    float64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
dtypes: float64(5), int64(3)
memory usage: 25.0 KB


In [ ]:
#checking for null values in each column
new_mpg_data.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model year      0
origin          0
dtype: int64

In [ ]:
#replacing nulls with mean
new_mpg_data.fillna(value=new_mpg_data.mean(), inplace=True)

In [ ]:
#summary of data after replacing nulls
new_mpg_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    float64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
dtypes: float64(5), int64(3)
memory usage: 25.0 KB


In [ ]:
#checking for null values in each column after replacing nulls
new_mpg_data.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
dtype: int64

In [ ]:
#values for new origin dummy variable
dummy = pd.get_dummies(new_mpg_data.origin, prefix='origin')
dummy.head(5)

origin_1  origin_2  origin_3
0         1         0         0
1         1         0         0
2         1         0         0
3         1         0         0
4         1         0         0

In [ ]:
#table with origin values included
data1 = new_mpg_data.drop(columns=['origin'])
data2 = pd.concat([data1, dummy], axis = 1)
data2.head(5)

mpg  cylinders  displacement  ...  origin_1  origin_2  origin_3
0  18.0          8         307.0  ...         1         0         0
1  15.0          8         350.0  ...         1         0         0
2  18.0          8         318.0  ...         1         0         0
3  16.0          8         304.0  ...         1         0         0
4  17.0          8         302.0  ...         1         0         0

[5 rows x 10 columns]

In [ ]:
#setting seed
import numpy as np
np.random.seed(1)
#creating features and labels
X = np.array(data2.drop(['mpg'], 1))
y = np.array(data2['mpg'])

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
model = LinearRegression(fit_intercept=True)

In [ ]:
#splitting data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
#Train shape
X_train.shape, y_train.shape

((318, 9), (318,))

In [ ]:
#Test shape
X_test.shape, y_test.shape

((80, 9), (80,))

In [ ]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
#coefficients of the model
model.coef_

array([-0.40247363,  0.02517027, -0.02090317, -0.00666591,  0.19107804,
        0.76544926, -1.92519814,  0.72404785,  1.20115029])

In [ ]:
#Model prediction
model2 = model.predict(X_test)

In [ ]:
#Calculating Mean Squared Error
np.mean((model2-y_test)**2)

10.992214962524361

In [ ]:
#Problem 2
url='http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'

In [ ]:
#loading dataset
wine_data = pd.read_csv(url, sep = ';', na_values = ['?', ' ?', ' ? ', '? '])

In [ ]:
#first 5 rows of wine data
wine_data.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [ ]:
#summary of wine data
wine_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [ ]:
#creating label vector and feature matrix
np.random.seed(123)
from sklearn import preprocessing
X = np.array(wine_data.drop(['quality'], 1))
y = np.array(wine_data['quality'])

In [ ]:
#splitting training set and testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
#preprocessing training set
scaler = preprocessing.StandardScaler().fit(X_train)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [ ]:
#preprocessing testing set
scaler2 = preprocessing.StandardScaler().fit(X_test)
scaler2

StandardScaler(copy=True, with_mean=True, with_std=True)

In [ ]:
#mean of training set
scaler.mean_

array([ 8.33737295,  0.53      ,  0.27218139,  2.55316654,  0.08702424,
       16.03283815, 47.11415168,  0.99675746,  3.30982799,  0.6590774 ,
       10.41399531])

In [ ]:
#Standard deviation of training set
scaler.scale_

array([1.73425985e+00, 1.82472378e-01, 1.95531020e-01, 1.45198085e+00,
       4.77823303e-02, 1.05168289e+01, 3.35710749e+01, 1.88171740e-03,
       1.53907566e-01, 1.74777221e-01, 1.06089277e+00])

In [ ]:
X_train_transformed = scaler.transform(X_train)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
import numpy as np
clf = RandomForestClassifier(n_estimators=300)
clf.fit(X_train_transformed, y_train)




RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=300,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
#5-fold accuracies
cross_val_score(clf, X_train_transformed, y_train, cv=5)

array([0.62109375, 0.625     , 0.671875  , 0.65625   , 0.69411765])

In [ ]:
#mean of 5-fold cross validation
np.mean(cross_val_score(clf, X_train_transformed, y_train, cv=5))

0.6528799019607844

In [ ]:
#standard deviation of 5-fold cross validation
np.std(cross_val_score(clf, X_train_transformed, y_train, cv=5))

0.01964190850214515

In [ ]:
#gridsearch parameters
from sklearn.model_selection import GridSearchCV
param_grid = {
                 'n_estimators': [100, 300, 500, 800, 1000]
             }

In [ ]:
#best parameters
grid_clf = GridSearchCV(clf, param_grid, cv=5)
grid_clf.fit(X_train_transformed, y_train)
grid_clf.best_params_

{'n_estimators': 100}

In [ ]:
#testing accuracy
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train_transformed, y_train)
X_test_transformed = scaler.transform(X_test)
clf.score(X_test_transformed, y_test)

0.725